services:
  - type: web
    name: pos-backend
    runtime: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: free
    region: singapore
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: "POS Backend"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-small-sea-b3617j9t.c-4.ap-southeast-1.aws.neon.tech
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: DB_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ENCRYPTION_KEY
        generateValue: true
      - key: FORCE_HTTPS
        value: "true"
      - key: TLS_HSTS_ENABLED
        value: "true"
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
